config/routes.rb
Rails.application.routes.draw do
  get 'userpages/index'
  get 'mypages/index'
  get 'sessions/new'

  root 'pages#index'

  resources :users do
    collection do 
      get 'users/auto_complete'
    end
  end
  
  resources :topics do
    post 'add' => 'favorites#create'
    delete '/add' => 'favorites#delete'
    collection do
      get :search
      get 'topics/auto_complete'
    end
    resources :comments, only: [:create,:destroy]
  end

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'favorites/index'
  post '/favorites', to: 'favorites#create' 
  post '/favorites/delete', to: 'favorites#delete'

  get 'mypages/myspot'
  get 'mypages/mypost'

  # get 'userpages/index'
  # get 'userpages/myspot'
  # get 'userpages/mypost'
  # get 'userpages/edit'
  resources :userpages do
    get 'myspot'
    get 'mypost'
  end

  # get 'mypages/test_update'

  # post '/comments', to: 'comments#create'
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :comment,  presence: true

    belongs_to :user
    belongs_to :topic
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @topic = Topic.find(params[:topic_id])
        #投稿に紐づいたコメントを作成。
        @comment = @topic.comments.build(comment_params)
        @comment.user_id = current_user.id

        @comment.save 
        render :index
    end

    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        render :index
    end

    private 
    def comment_params
        params.require(:comment).permit(:comment, :item_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [topic, comment], url: topic_comments_path(@topic) ) do |f| %>
    <div class="form-group">
        <%= f.text_area :comment, class: "input-comment-text" %>
        <%= button_tag :type => "submit", :class => "btn btn-outline-dark comment-submit float-right" do %>
            送信  <i class="fas fa-paper-plane"></i>
        <% end %>
    </div>
<% end %>

app/views/comments/_index.html.erb
<!-- コメント内容（3件以内）---------->
<ul class="list-group list-group-flush">
<h5><%= comments.count %>件のコメント<h4>
<h6 class="more" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">もっと見る....</h6>
<% comments.first(3).each do |comment| %>
    <% unless comment.id.nil? %>
        <li class="list-group-item comment-content">
            <div class="comment-box">
                <div class="comment-avatar">
                    <!--ユーザの顔-->
                </div>
                <div class="comment-text">
                    <!--<p>ユーザへのリンク</p>-->
                    <div class="comment-entry">
                        <%= comment.comment %>
                        <% if comment.user == current_user %>
                            <%= link_to(topic_comment_path(comment.topic_id, comment.id), method: :delete, remote: true, class: "comment_destroy") do %>
                                <i class="fas fa-trash delete-tag" style="color: black;"></i>
                            <% end %>
                        <% end %>
                    </div>
                    <span class="comment-date pull-right">
                        <%= comment.user.name %>
                        <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                    </span>
                </div>
            </div>
        </li>
    <% end %>
<% end %>
<!-- コメント内容（4件目以降）---------->
<div class="collapse" id="collapseExample">
    <% comments.offset(3).each do |comment| %>
        <% unless comment.id.nil? %>
            <li class="list-group-item comment-content">
                <div class="comment-box">
                    <div class="comment-avatar">
                        <!--ユーザの顔-->
                    </div>
                    <div class="comment-text">
                        <!--<p>ユーザへのリンク</p>-->
                        <div class="comment-entry">
                            <%= comment.comment %>
                            <% if comment.user == current_user %>
                                <%= link_to(topic_comment_path(comment.topic_id, comment.id), method: :delete, remote: true, class: "comment_destroy") do %>
                                    <i class="fas fa-trash delete-tag" style="color: black;"></i>
                                <% end %>
                            <% end %>
                        </div>
                        <span class="comment-date pull-right">
                            <%= comment.user.name %>
                            <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                        </span>
                    </div>
                </div>
            </li>
        <% end %>
    <% end %>
</div>
</ul>

app/views/comments/index.js.erb
$('#comments_area').html("<%= escape_javascript(render partial: 'comments/index', locals: { comments: @comment.topic.comments.order(id: :desc) }) %>");
$("textarea").val('');