config/routes.rb
Rails.application.routes.draw do
  get 'userpages/index'
  get 'mypages/index'
  get 'sessions/new'

  root 'pages#index'

  resources :users do
    collection do 
      get 'users/auto_complete'
    end
  end
  
  resources :topics do
    post 'add' => 'favorites#create'
    delete '/add' => 'favorites#delete'
    collection do
      get :search
      get 'topics/auto_complete'
    end
    resources :comments, only: [:create,:destroy]
  end

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'favorites/index'
  post '/favorites', to: 'favorites#create' 
  post '/favorites/delete', to: 'favorites#delete'

  get 'mypages/myspot'
  get 'mypages/mypost'

  # get 'userpages/index'
  # get 'userpages/myspot'
  # get 'userpages/mypost'
  # get 'userpages/edit'
  resources :userpages do
    get 'myspot'
    get 'mypost'
  end

  # get 'mypages/test_update'

  # post '/comments', to: 'comments#create'
end

app/controllers/userpages_controller.rb
class UserpagesController < ApplicationController

    def index
        # リンクされてきたユーザIDを引数として受け取る
        user_id = params[:id]
        @user = User.find(user_id)

        # ユーザページの投稿したもの上位４件
        @my_topics = @user.topics.order(updated_at: :desc).limit(4)
        # ユーザの投稿数
        @topic_cnt = @user.topics.count

        # ユーザページのいいねしたもの上位４件
        @my_fav_topics = @user.favorite_topics.order(updated_at: :desc).limit(4)
    end

    # Myスポット一覧
    def myspot
        # リンクされてきたユーザIDを引数として受け取る
        user_id = params[:userpage_id]
        @user = User.find(user_id)

        @favorite_topics = @user.favorite_topics.order(updated_at: :desc)
    end
    
    #投稿一覧
    def mypost
        # リンクされてきたユーザIDを引数として受け取る
        user_id = params[:userpage_id]
        @user = User.find(user_id)

        @mytopics = @user.topics.order(updated_at: :desc)
    end
end

app/helpers/userpages_helper.rb
module UserpagesHelper
end

app/views/userpages/index.html.erb
<div class="userpage-wrapper" >
    <div class="container mypage-container userpage-container">
        <div class="row">
            <!-- ユーザ情報 -->
            <div class="col-lg-4 col-xs-12">
                <div class="card-inclusion mb-4">
                    <h1 class="user-name"><%= @user.name %>さん</h1>
                    <hr>
                    <% if @user.icon.url.nil? %>
                        <div class="user-icon">
                            <i class="far fa-user fa-3x"></i>
                        </div>
                    <% else %>
                        <%= image_tag @user.icon.url, class: "new-topic-picture" %>
                    <% end %>
                    <div class="card-body">
                        <h3>自己紹介</h2>
                            <p><%= @user.introduction %></p>
                        <h3>最寄駅</h3>
                            <p><%= @user.station %></p>
                        <h3><%= @user.name %>さんの投稿数</h3>
                            <p><%= @topic_cnt %>件 投稿</p>
                    </div>
                    <!-- 自分のアカウントページなら編集可能 -->
                    <% if @user == current_user %>
                        <hr>
                        <div class="intro-link">
                            <%= link_to edit_user_path(id: current_user.id) do %>
                                <div><i class="far fa-address-card"></i>プロフィールを編集する</div>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
            <!-- ユーザ投稿表示部分-->
            <div class="col-lg-8 col-xs-12">
                <!-- 対象ユーザ投稿一覧 -->
                <div class="card-inclusion mb-4">
                    <div class="text-center title-grid">
                        <h2 calss="fw-bolder title-left"><%= @user.name %>さんの最新投稿 </h2>
                        <%= link_to userpage_mypost_path(userpage_id: @user.id) do %>
                            <button type="button" class="btn btn-success title-right">一覧へ</button>
                        <% end %>
                    </div>
                    <!-- Topicsを取得してLOOPさせる。 -->
                    <div class="row">
                    <% @my_topics.each do |my_topic| %>
                        <div class="col-lg-6 col-xs-12">
                            <div class="card mb-4">
                            <% if my_topic.picture_1.url.nil? %>
                                <div class="new_img_field">
                                    <i class="fas fa-images"></i>
                                </div>
                            <% else %>
                                <%= image_tag my_topic.picture_1.url, class: "new-topic-picture" %>
                            <% end %>
                                <div class="card-body">
                                    <div class="small text-muted"><strong>投稿者：</strong><%= my_topic.user.name %></div>
                                    <div class="small text-muted"><strong>投稿日：</strong><%= my_topic.created_at.strftime('%Y/%m/%d %H:%M:%S') %></div>
                                    <h2 class="card-title h4"><%= my_topic.title %></h2>
                                    <p class="card-text"><%= my_topic.description %></p>
                                    <a class="btn btn-primary" href="/topics/<%= my_topic.id %>">投稿へ →</a>
                                </div>
                            </div>
                        </div>
                    <% end %>
                    </div>
                </div>
                <!-- 対象ユーザいいね一覧 -->
                <div class="card-inclusion mb-4">
                    <div class="text-center title-grid">
                        <h2 calss="fw-bolder title-left"><%= @user.name %>さんのMyスポット</h2>
                        <%= link_to userpage_myspot_path(userpage_id: @user.id) do %>
                            <button type="button" class="btn btn-success title-right">一覧へ</button>
                        <% end %>
                    </div>
                    <!-- Topicsを取得してLOOPさせる。 -->
                    <div class="row">
                    <% @my_fav_topics.each do |my_fav_topic| %>
                        <div class="col-lg-6 col-xs-12">
                            <div class="card mb-4">
                            <% if my_fav_topic.picture_1.url.nil? %>
                                <div class="new_img_field">
                                    <i class="fas fa-images"></i>
                                </div>
                            <% else %>
                                <%= image_tag my_fav_topic.picture_1.url, class: "new-topic-picture" %>
                            <% end %>
                                <div class="card-body">
                                    <div class="small text-muted"><strong>投稿者：</strong><%= my_fav_topic.user.name %></div>
                                    <div class="small text-muted"><strong>投稿日：</strong><%= my_fav_topic.created_at.strftime('%Y/%m/%d %H:%M:%S') %></div>
                                    <h2 class="card-title h4"><%= my_fav_topic.title %></h2>
                                    <p class="card-text"><%= my_fav_topic.description %></p>
                                    <a class="btn btn-primary" href="/topics/<%= my_fav_topic.id %>">投稿へ →</a>
                                </div>
                            </div>
                        </div>
                    <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/userpages/mypost.html.erb
<header class="mypage-wrapper">
    <div class="container">
        <!-- アカウントページから移動してきたユーザの投稿一覧　-->
        <div class="text-center">
            <h2 calss="fw-bolder"><%= @user.name %>さん　投稿一覧</h2>
        </div>
    </div>
</header>

<%= render 'mypages/spot', mytopics: @mytopics %>

app/views/userpages/myspot.html.erb
<header class="mypage-wrapper">
    <div class="container">
        <!-- Myスポット（アカウントページから移動してきたユーザのお気に入り一覧）　-->
        <div class="text-center">
            <h2 calss="fw-bolder"><%= @user.name %>さん　Myスポット一覧</h2>
        </div>
    </div>
</header>

<%= render 'mypages/spot', mytopics: @favorite_topics %>