config/routes.rb
Rails.application.routes.draw do
  get 'userpages/index'
  get 'mypages/index'
  get 'sessions/new'

  root 'pages#index'

  resources :users do
    collection do 
      get 'users/auto_complete'
    end
  end
  
  resources :topics do
    post 'add' => 'favorites#create'
    delete '/add' => 'favorites#delete'
    collection do
      get :search
      get 'topics/auto_complete'
    end
    resources :comments, only: [:create,:destroy]
  end

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'favorites/index'
  post '/favorites', to: 'favorites#create' 
  post '/favorites/delete', to: 'favorites#delete'

  get 'mypages/myspot'
  get 'mypages/mypost'

  # get 'userpages/index'
  # get 'userpages/myspot'
  # get 'userpages/mypost'
  # get 'userpages/edit'
  resources :userpages do
    get 'myspot'
    get 'mypost'
  end

  # get 'mypages/test_update'

  # post '/comments', to: 'comments#create'
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController

  def index
    # 自分がいいねした投稿上位３件
    id = current_user.id
    query = "select topics.* from topics inner join favorites on topics.id = favorites.topic_id
    where favorites.user_id = #{id} order by topics.updated_at desc LIMIT 3"
    @topics = Topic.find_by_sql([query])

    # いいね数上位5件を取得
    query_ranking = "select topics.*,ranking.* from topics
    inner join (select topic_id ,count(1) as rank from favorites group by topic_id) as ranking
    on topics.id = ranking.topic_id
    order by ranking.rank desc, topics.updated_at desc LIMIT 5"
    @topics_rank = Topic.find_by_sql([query_ranking])
    gon.topics_rank = @topics_rank

    # 自分の投稿したもの上位3件
    @my_topics = current_user.topics.order(updated_at: :desc).limit(3)

    # 前投稿で作成日が最新のもの上位４件
    @new_topics = Topic.all.order(created_at: :desc).limit(4)

    @env = get_apikey
  end

  def myspot
    @favorite_topics = current_user.favorite_topics.order(updated_at: :desc)
  end

  def mypost
    @mytopics = current_user.topics.order(updated_at: :desc)
  end

  # def test_update
  #   sql = "UPDATE stations SET name = CONCAT(name,'駅')"
  #   ActiveRecord::Base.connection.execute(sql)
  # end

end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/views/mypages/_spot.html.erb
<div class="container mypage-container">
    <div class="row">
        <div class="col-md-offset-2 col-md-8 col-md-offset-2 col-xs-12">
            <div class="myspotpage-container">
                <!-- Topicsを取得してLOOPさせる。 -->
                <div class="row">
                <% mytopics.each do |mytopic| %>
                    <div class="col-lg-6 col-xs-12">
                        <div class="card mb-4 myspot-card">
                            <% if mytopic.picture_1.url.nil? %>
                                <div class="new_img_field">
                                    <i class="fas fa-images"></i>
                                </div>
                            <% else %>
                                <%= image_tag mytopic.picture_1.url, class: "new-topic-picture" %>
                            <% end %>
                            <div class="card-body">
                                <div class="small text-muted"><strong>投稿者：</strong><%= mytopic.user.name %></div>
                                <div class="small text-muted"><strong>投稿日：</strong><%= mytopic.created_at.strftime('%Y/%m/%d %H:%M:%S') %></div>
                                <h2 class="card-title h4"><%= mytopic.title %></h2>
                                <p class="card-text"><%= mytopic.description %></p>
                                <a class="btn btn-primary" href="/topics/<%= mytopic.id %>">投稿へ →</a>
                            </div>
                        </div>
                    </div>
                <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/mypages/index.html.erb
<header class=" mypage-wrapper">
    <div class="container">
        <div class="text-center my-5 ">
            <div class="mypage-header">
                <h1 class="fw-bolder">Welcome to Localmapping!</h1>
                <p class="lead mb-0">まちに身を置き、まちなかを体感しよう</p>
            </div>
            <p class="lead mb-0 pull-right">ようこそ！　<%= current_user.name %>さん</p>
            <%= hidden_field_tag :my_station, current_user.station %>
        </div>
    </div>
</header>
<!-- Page content-->
<div class="container mypage-container">
    <div class="row">
        <!-- マイページ（メイン部分）-->
        <div class="col-lg-8 col-xs-12">
            <!-- いいね順のランキング-->
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title ranking-title">人気ランキング</h2>
                </div>
                <div class="card-img-top card-ranking-map" id='map_mypage'></div>
                <ul class="list-group list-group-flush list-spot-ranking">
                    <% cnt = 1 %>
                    <% @topics_rank.each do |rank| %>
                        <li class="list-group-item">
                            <div class="rank-spot-container">
                                <div class="rank-spot-top">
                                    <div><strong>No<%= cnt %></strong>　<%= rank.rank %> いいね <i class="far fa-thumbs-up fa-lg"></i></div>
                                </div>
                                <div class="rank-spot-left">
                                    <% unless rank.picture_1.url.nil? %>
                                        <%= image_tag rank.picture_1.url, class: "rank-spot-picture" %>
                                    <% end %>
                                </div>
                                <div class="rank-spot-right">
                                    <div><strong>タイトル：</strong><%= rank.title %></div>
                                    <div><strong>最寄駅　：</strong><%= rank.station %></div>
                                    <div><strong>投稿者　：</strong><%= rank.user.name %></div>
                                    <div><strong>更新日　：</strong><%= rank.updated_at.strftime('%Y/%m/%d %H:%M:%S') %></div>
                                </div>
                                <div class="rank-spot-show">
                                    <a class="btn btn-primary" href="/topics/<%= rank.id %>">投稿へ →</a>
                                </div>
                            </div>
                        </li>
                    <% cnt += 1%>
                    <% end %>
                    <div id="debug"></div>
                </ul>
            </div>
            <!-- オススメ（投稿日が最新のもの上位４件）　-->
            <div class="text-center">
                <h2 calss="fw-bolder">最新オススメスポット</h2>
            </div>
            <!-- Topicsを取得してLOOPさせる。 -->
            <div class="row">
            <% @new_topics.each do |new_topic| %>
                <div class="col-lg-6 col-xs-12">
                    <div class="card mb-4">
                        <% if new_topic.picture_1.url.nil? %>
                            <div class="new_img_field">
                                <i class="fas fa-images"></i>
                            </div>
                        <% else %>
                            <%= image_tag new_topic.picture_1.url, class: "new-topic-picture" %>
                        <% end %>
                        <div class="card-body">
                            <div class="small text-muted"><strong>投稿者：</strong><%= new_topic.user.name %></div>
                            <div class="small text-muted"><strong>投稿日：</strong><%= new_topic.created_at.strftime('%Y/%m/%d %H:%M:%S') %></div>
                            <h2 class="card-title h4"><%= new_topic.title %></h2>
                            <p class="card-text"><%= new_topic.description %></p>
                            <a class="btn btn-primary" href="/topics/<%= new_topic.id %>">投稿へ →</a>
                        </div>
                    </div>
                </div>
            <% end %>
            </div>
        </div>
        <!-- 左部分のコンテナ(Myスポット、投稿一覧(簡易的)、MyPage(未実装)）) -->
        <% if logged_in? %>
            <div class="col-lg-4 col-xs-12">
                <!-- Myスポット -->
                <div class="card mb-4">
                    <div class="card-header">
                        <% if logged_in? %>
                            <%= link_to mypages_myspot_path do %>
                                Myスポット
                            <% end %>
                        <% else %>
                            <a href="#">Myスポット</a>
                        <% end %>
                    </div>
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            <% @topics.each do |topic| %>
                                    <li class="list-group-item">
                                        <div class="myspot-container">
                                            <div class="myspot-left">
                                                <% unless topic.picture_1.url.nil? %>
                                                    <%= image_tag topic.picture_1.url, class: "myspot-picture" %>
                                                <% end %>
                                            </div>
                                            <div class="myspot-right">
                                                <div><strong>タイトル：</strong><%= topic.title %></div>
                                                <div><strong>最寄駅　：</strong><%= topic.station %></div>
                                                <div><strong>投稿者　：</strong><%= topic.user.name %></div>
                                                <div><strong>更新日　：</strong><%= topic.updated_at.strftime('%Y/%m/%d %H:%M:%S') %></div>
                                            </div>
                                            <div class="myspot-show">
                                                <a class="btn btn-primary" href="/topics/<%= topic.id %>">投稿へ →</a>
                                            </div>
                                        </div>
                                    </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
                <!-- 投稿一覧-->
                <div class="card mb-4">
                    <div class="card-header">
                        <% if logged_in? %>
                            <%= link_to mypages_mypost_path do %>
                                自分の投稿一覧
                            <% end %>
                        <% else %>
                            <a href="#">自分の投稿一覧</a>
                        <% end %>
                    </div>
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            <% @my_topics.each do |topic| %>
                                    <li class="list-group-item">
                                        <div class="mysubmit-container">
                                            <div class="mysubmit-left">
                                                <% unless topic.picture_1.url.nil? %>
                                                    <%= image_tag topic.picture_1.url, class: "mysubmit-picture" %>
                                                <% end %>
                                            </div>
                                            <div class="mysubmit-right">
                                                <div><strong>タイトル：</strong><%= topic.title %></div>
                                                <div><strong>最寄駅　：</strong><%= topic.station %></div>
                                                <div><strong>投稿者　：</strong><%= topic.user.name %></div>
                                                <div><strong>更新日　：</strong><%= topic.updated_at.strftime('%Y/%m/%d %H:%M:%S') %></div>
                                            </div>
                                            <div class="mysubmit-show">
                                                <a class="btn btn-primary" href="/topics/<%= topic.id %>">投稿へ →</a>
                                            </div>
                                            <div class="mysubmit-edit">
                                                <a class="btn btn-success" href="/topics/<%= topic.id %>/edit">編集 →</a>
                                            </div>
                                        </div>
                                    </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
                <!-- ユーザ情報 -->
                <!--TODO:ユーザ情報ページ、ユーザ情報編集機能
                <div class="card mb-4">
                    <div class="card-header">Side Widget</div>
                    <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
                </div>
                -->
            </div>
        <% end %>
    </div>
</div>



<script>

function initMap(){
    var geocoder
    const topics_rank = gon.topics_rank //Controllerで取得したいいねランキングの上位Topics
    var marker = []; // マーカーを複数表示させたいので、配列化
    var infoWindow = []; // 吹き出しを複数表示させたいので、配列化
    var latitude = [];
    var longitude = [];
    var mylatlng
    var my_station = document.getElementById('my_station').value;

    geocoder = new google.maps.Geocoder()

    var map = new google.maps.Map(document.getElementById('map_mypage'));//地図を作成する

    geo(aftergeo);

    function geo(callback){
        var cRef = topics_rank.length;
        // gonで定義したtopics分繰り返し加える処理を行う
        for (var i = 0; i < topics_rank.length; i++) {
            // topicsの緯度経度を取得
            latitude[i] = topics_rank[i]['latitude'];
            longitude[i] = topics_rank[i]['longitude'];

            (function(i) {
                geocoder.geocode( { 'address': my_station }, function(results, status) {
                    if (status == 'OK') {// statusがOKであれば
                        mylatlng = results[0].geometry.location;
                        marker[i] = new google.maps.Marker({
                            position: {lat: latitude[i], lng:longitude[i]},
                            map: map
                        });
                        // 変数iを変数idに代入
                        let id = topics_rank[i]['id']
                        let No = i + 1;
                        // infoWindowは吹き出し
                        infoWindow[i] = new google.maps.InfoWindow({
                            // contentで中身を指定
                            // 文字にリンクを貼り付けた形で表示
                            content: `No${No}：<a href='/topics/${id}' class='map_link'>${topics_rank[i].title}</a>`
                        });
                        // markerがクリックされた時、
                        marker[i].addListener("click", function(){
                            // infoWindowを表示
                            infoWindow[i].open(map, marker[i]);
                        });
                    } else {// 失敗した場合
                    }//if文の終了。
                    if (--cRef <= 0) {
                        callback();//全て取得できたらaftergeo実行
                    }
                });////function(results, status)及びgeocoder.geocodeの終了
            }) (i);
        } //for文の終了
    }//function geo終了

    function aftergeo(){
        var opt = {
            center: mylatlng,
            zoom: 14 // 地図のズームを指定
        };//地図作成のオプションのうちcenterとzoomは必須
        map.setOptions(opt);//オプションをmapにセット
    }//function aftergeo終了
};//function initMap終了

</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= @env %>&callback=initMap" async defer></script>

app/views/mypages/mypost.html.erb
<header class=" mypage-wrapper">
    <div class="container">
        <!-- 自分の投稿一覧　-->
        <div class="text-center">
            <h2 calss="fw-bolder">投稿一覧</h2>
        </div>
    </div>
</header>

<%= render 'mypages/spot', mytopics: @mytopics %>

app/views/mypages/myspot.html.erb
<header class=" mypage-wrapper">
    <div class="container">
        <!-- Myスポット（自分のお気に入り一覧）　-->
        <div class="text-center">
            <h2 calss="fw-bolder">Myスポット一覧</h2>
        </div>
    </div>
</header>

<%= render 'mypages/spot', mytopics: @favorite_topics %>

app/views/mypages/test_update.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1> AAAAAA</h1>