config/routes.rb
Rails.application.routes.draw do
  get 'userpages/index'
  get 'mypages/index'
  get 'sessions/new'

  root 'pages#index'

  resources :users do
    collection do 
      get 'users/auto_complete'
    end
  end
  
  resources :topics do
    post 'add' => 'favorites#create'
    delete '/add' => 'favorites#delete'
    collection do
      get :search
      get 'topics/auto_complete'
    end
    resources :comments, only: [:create,:destroy]
  end

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'favorites/index'
  post '/favorites', to: 'favorites#create' 
  post '/favorites/delete', to: 'favorites#delete'

  get 'mypages/myspot'
  get 'mypages/mypost'

  # get 'userpages/index'
  # get 'userpages/myspot'
  # get 'userpages/mypost'
  # get 'userpages/edit'
  resources :userpages do
    get 'myspot'
    get 'mypost'
  end

  # get 'mypages/test_update'

  # post '/comments', to: 'comments#create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Local Mapping</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <nav class="navbar navbar-default navbar-fixed-top navbar-custom">
      <div class="container">
        <% if logged_in? %>
          <%= link_to mypages_index_path do %>
            <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
          <% end %>
        <% else %>
          <%= link_to root_path do %>
            <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
          <% end %>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to mypages_index_path do %>
                <div class="nav-center">マイページ</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to userpages_path(id: current_user.id) do %>
                <div class="nav-center">アカウント</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to search_topics_path do %>
                <div class="nav-center">検索</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_topic_path do %>
                <div class="nav-center">投稿</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to logout_path, method: :delete do %>
                <div class="nav-center">ログアウト</div>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to new_user_path do %>
                <div class="nav-center">新規登録</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to login_path do %>
                <div class="nav-center">ログイン</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to mypages_index_path do %>
                <div class="nav-center">メインページ</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to search_topics_path do %>
                <div class="nav-center">検索</div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(2000);
      });

    </script>
  </body>
</html>